# Sample workflow for building and deploying an Astro site to a self-hosted server with GitHub Actions and a self-hosted runner.
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site self-hosted

on:
  # Runs on pushes targeting the default branch
  push:
    # branches: ["master", "github-actions"]
    branches: ["github-actions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder
  NGINX_PATH: "/home/magellan/site-astro"

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Create nginx html folder
        run: |
          mkdir -p ${{ env.NGINX_PATH }}
        working-directory: ${{ env.BUILD_PATH }}

      - name: Copy to nginx html folder
        run: |
          cp -r ${{ env.BUILD_PATH }}/dist/* ${{ env.NGINX_PATH }}
        working-directory: ${{ env.BUILD_PATH }}
